phpbb/documentation

development/index.rst
development/update/index.rst
development/update/modification_to_extension.rst

@naderman 
this is a copy of https://github.com/nickvergessen/howto-convert-phpbb30mod-to-phpbb31ext just with rst mark up instead of markdown.

Move nickvergessen/howto-convert-phpbb30mod-to-phpbb31ext to doc

---

development/development/coding_guidelines.rst
development/index.rst

Replacing https://wiki.phpbb.com/Coding_guidelines

Add coding guidelines

---

development/index.rst
development/testing/functional_testing.rst
development/testing/index.rst
development/testing/unit_testing.rst

Replacing https://wiki.phpbb.com/Automated_Tests

Add documentation for testing

---

development/index.rst
development/migrations/data_changes.rst
development/migrations/dependencies.rst
development/migrations/extensions.rst
development/migrations/getting_started.rst
development/migrations/index.rst
development/migrations/schema_changes.rst
development/migrations/tools/config.rst
development/migrations/tools/config_text.rst
development/migrations/tools/index.rst
development/migrations/tools/module.rst
development/migrations/tools/permission.rst

Replaces https://wiki.phpbb.com/Category:Migrations

Add docs about migrations

---

development/extensions/modification_to_extension.rst
development/testing/functional_testing.rst
development/testing/unit_testing.rst

Add file names when we add a code block of the complete file

---

development/language/usage.rst

Add JavaScript lang key documentation

---

development/language/usage.rst

Fix type in note of language/usage

---

development/extensions/modification_to_extension.rst
development/extensions/tutorial_basics.rst

Fix the link to the migration docs

---

development/files/filespec.rst
development/files/overview.rst
development/files/upload.rst

Removed extra accent mark and state clean_filename() method.
Fixes #50

Minor corrections to files documentation

---

development/language/index.rst
development/language/validation.rst

Moving https://github.com/phpbb/phpbb-translation-policies to the docs

Add https://github.com/phpbb/phpbb-translation-policies to the docs

---

development/extensions/index.rst

Ext Docs Part 0 - Refactor index links

---

development/development/phpstorm.rst
development/extensions/modification_to_extension.rst
development/extensions/skeleton_extension.rst
development/extensions/tutorial_testing.rst

Corrections in other doc files

---

development/extensions/new_in_rhea.rst

This documentation is for extension developers. It explains what's changed for them with phpBB 3.2 and is based on the sticky topic from here: https://www.phpbb.com/community/viewtopic.php?f=461&t=2349131

Add ext documentation for 3.2 updates

---

development/extensions/tutorial_key_concepts.rst

Modified explanation of how to use language functiond for 3.2

Update language docs for 3.2

---

development/extensions/tutorial_controllers.rst
development/extensions/tutorial_modules.rst
development/extensions/tutorial_testing.rst

Replace user->lang with language->lang

---

development/language/validation.rst

Changes validation section to new 3.2.x guidelines

---

development/language/validation.rst

File modified -  documentation/development/language/validation.rst
WEBSITE-1303

[ticket/1303] CDB Link in phpBB Development Documentation not working-1

---

.travis.yml
development/conf.py

Should fix builds with latest version of sphinx.

Fix build with latest sphinx

---

development/migrations/data_changes.rst

Also, show example of compatibility with multi step process

[ticket/15274] Document parameters for custom functions

---

development/conf.py
development/language/guidelines.rst
development/language/validation.rst

Add submission guidelines to docu and updates validation.rst

---

development/language/guidelines.rst

Make the list of files look good again. 
For #120

Add code:: to the list of files

---

development/extensions/tutorial_migrations.rst

Should be merged up through all branches ;)
Added a warning about the importance of not changing migration files after they have been used/installed.

Add note about changing migrations

---

documentation/ascraeus_doc.xml
documentation/content/en/chapters/admin_guide.xml
documentation/content/en/chapters/glossary.xml
documentation/content/en/chapters/moderator_guide.xml
documentation/content/en/chapters/quick_start_guide.xml
documentation/content/en/chapters/upgrade_guide.xml
documentation/content/en/chapters/user_guide.xml

Fix building of documentation by switching to https docbook link

---

development/language/validation.rst

Fixes #148 
Upstream merge to master, too!

Remove no longer existing language-keys from HTML-exeptions

---

development/extensions/skeleton_extension.rst

This should be merged after the next Skeleton extension update is released.

Update Skeleton extension documentation

---

development/cli/getting_started.rst

Add information for CLI install and update to docu

---

development/development/coding_guidelines.rst
development/development/git.rst
development/index.rst
development/language/guidelines.rst
development/language/validation.rst
development/testing/index.rst
development/testing/ui_testing.rst

Some of the git documentation was a bit outdated and documentation on UI tests was missing completely. Also fixed a few build issues.

Update Git instructions & add ui testing documentation

---

development/extensions/new_in_rhea_3.3.rst

If I missed anything, let me know.
If I was wrong about anything, let me know.

Whats New For phpBB 3.3 For Ext Authors

---

documentation/content/en/chapters/admin_guide.xml
documentation/content/en/chapters/quick_start_guide.xml
documentation/content/en/chapters/upgrade_guide.xml

Fix incorrect links and outdated info

---

readme.md

Fixes #144 
- Adds development documentation link
- Updates user documentation link to 3.3 and the redirected url

Development docs in README

---

development/index.rst
development/request/request.rst

Adds an entry for the request (`\phpbb\request\request`) class in the development docs.
Partially fixes #102 
**Table of Contents**
- Introduction
- Information
- Super globals
- Functions
- is_ajax
- is_secure
- is_set
- is_set_post
- variable
- file
- header
- server
- overwrite
- variable_names
- get_super_global
- request_var

Request class

---

development/development/css/css_guidelines.rst
development/development/css/css_specificity.rst
development/development/css/css_standards.rst
development/development/html/guidance.rst
development/development/html/index.rst
development/development/js/index.rst
development/development/php/character_set_and_encodings.rst
development/development/php/defaults.rst
development/development/php/index.rst
development/development/php/layout_guidelines.rst
development/development/php/templating.rst
development/extensions/tutorial_modules.rst
development/start/getting_started.rst
development/start/install.rst

Resolve incorrect formatting and invalid references

---

development/extensions/tutorial_testing.rst

See: https://github.com/phpbb/phpbb/pull/6043

Remove sami from the tutorial

---

development/extensions/tutorial_testing.rst

Fix invalid reference to section in extensions tutorial for testing

---

development/_static/css/phpbb.css

Use 100% width instead of float to not break layout

---

development/extensions/modification_to_extension.rst
development/extensions/new_in_rhea.rst
development/extensions/tutorial_advanced.rst
development/extensions/tutorial_authentication.rst
development/extensions/tutorial_controllers.rst
development/extensions/tutorial_events.rst
development/extensions/tutorial_key_concepts.rst
development/extensions/tutorial_modules.rst

Use TWIG syntax

---

documentation/content/en/chapters/upgrade_guide.xml

This already exists for 3.3.x. Fixes #233.

Remove duplicate section about 3.2.x minor updates

---

CONTRIBUTING.md
readme.md

Closes #56
Trying to add some help for contributors. Mostly info for Dev docs, since I'm not sure what is needed for the other XML documentation

Create Contributing Docs

---

development/migrations/tools/permission.rst

Add Role Exists documentation

---

development/cli/getting_started.rst

This will avoid, that there is written:
`–safe-mode`
it should be:
`--safe-mode`

Update cli options format

---

development/extensions/index.rst
development/extensions/permission_system.rst
development/extensions/tutorial_parsing_text.rst
development/extensions/tutorial_templates.rst
documentation/content/en/chapters/admin_guide.xml
documentation/content/en/chapters/server_guide.xml
documentation/rhea_doc.xml

Add tutorial for parsing text from wiki

---

documentation/content/en/chapters/server_guide.xml

Added a link to a good stopwords file for e.g. sphinx.

Add link to stopwords file for sphinx

---

development/development/upgrade/400.rst

Documentation update on https://github.com/phpbb/phpbb/pull/6533

[ticket/17151] Document functions removal
