development/index.rst, development/language/index.rst, development/language/plurals.rst, development/language/usage.rst
https://wiki.phpbb.com/Plural_Rules in rst format
=> Add https://wiki.phpbb.com/Plural_Rules to doc

development/development/coding_guidelines.rst
https://github.com/phpbb/phpbb/pull/3668
=> Added docs for js linting

development/language/index.rst, development/language/usage.rst
=> Add a sample how to load an extension language file

development/language/usage.rst
@MateBartus please review https://github.com/phpbb/documentation/commit/6bf972a5a69aefde375ad737a10df2491540cd0e
=> Issue/21 language system changes in 3.2

development/extensions/modification_to_extension.rst, development/extensions/tutorial_controllers.rst
We should promote the practice of wrapping these in single quotes, as that is preferred by Symfony and will eventually be mandatory (non quoted method is already deprecated)
=> Wrap config services starting with % and @ in quotes

development/files/filespec.rst, development/files/index.rst, development/files/overview.rst, development/files/upload.rst, development/index.rst
=> [ticket/50]  Add documentation for new files classes

development/extensions/tutorial_basics.rst, development/extensions/tutorial_events.rst
Update the Basics and Events page. Split it up into two pages.
These docs also contain info copied from the wiki pages:
https://wiki.phpbb.com/Extension_meta_data
https://wiki.phpbb.com/Developing_Extensions
https://wiki.phpbb.com/Category:Events_and_Listeners
https://wiki.phpbb.com/Add_Events
https://wiki.phpbb.com/Add_Listeners
https://wiki.phpbb.com/Add_Template_Listeners
PR Misc. #90 
=> Ext Docs Part 1 - Basics and Events

development/extensions/tutorial_key_concepts.rst
This is new documentation. It's information mostly comes from the Writing Extensions page on .com.
PR Misc. #90 
=> Ext Docs Part 2 - Key Concepts

development/extensions/tutorial_controllers.rst
Update the controllers doc.
Includes info copied from the wiki:
https://wiki.phpbb.com/Controller
PR Misc. #90 
=> Ext Docs Part 3 - Controllers

development/extensions/tutorial_permissions.rst
New docs about permissions. Most of this info comes from the writing extension page at .com.
PR Misc. #90 
=> Ext Docs Part 5 - Permissions

development/extensions/tutorial_authentication.rst
New extension docs about authentication plugins.
Copied from the wiki and updated:
https://wiki.phpbb.com/Authentication_providers
https://wiki.phpbb.com/OAuth_Providers
PR Misc. #90 
=> Ext Docs Part 6 - Authentication

development/extensions/tutorial_advanced.rst
Updated docs. Renamed docs.
Added new docs from the writing extensions guide on .com (using ext.php) and copied from the wiki (using version check JSON files):
https://wiki.phpbb.com/Extension_meta_data
PR Misc. #90 
=> Ext Docs Part 7 - Advanced lessons

development/extensions/tutorial_authentication.rst
Please take a look at my comment at https://www.phpbb.com/community/posting.php?mode=quote&f=461&p=14577286#pr14577276
I created my authentication provider and named it eg. "myext.authentication.MyAuthenticationProvider".
But my authentication provider will not be found.
The authentication provider service name has to start with "auth.provider." e.g. "auth.provider.MyAuthenticationProvider".
That check is hard coded in phpBB file "auth/provider_collection" method "get_provider" of v3.1.10.
If service name does not start with "auth.provider" the default provider "db" will be used. 
Can you please verify?
Greetz Anthony
=> Update AuthenticationProvider Documentation

development/extensions/new_in_rhea.rst
* smiley_text() is specific to the 3.1 formatting and shouldn't be used on 3.2.
* enable_bbcode() and the other functions described are part of the parser service's API.
* get_parser() retrieves the underlying s9e\TextFormatter\Parser instance, which has a different API.
=> Fixes related to text formatting

development/migrations/data_changes.rst
Remove unneeded references, remove mention to call user_func_array.
=> [ticket/15274] Fix "custom" migration documentation

development/development/coding_guidelines.rst
Fix the links in the CSS coding guidelines section
=> fix css coding guidelines links

development/extensions/tutorial_bbcodes.rst
The return value is not used in TextFormatter 1.x and tag invalidation must be explicit. This example will work both on 0.x and 1.x.
=> Update the BBCodes example for forward compatibility

development/extensions/tutorial_testing.rst
EPV minim version has changed from 5.5. to 5.6:
"require": {
"php": ">=5.5.9",
=> Changing php version for EPV execution from 5.5 to 5.6

development/db/dbal.rst
Updated the DBAL documentation:
- Removed no longer used `includes/db/` references
- Updated syntax to use `:class:` to better indicate things
- Added `<br>` elements to prevent needlessly scrolling (mostly in tables)
- Added several functions
- `sql_build_query`
- `sql_like_expression`
- mentions `sql_not_like_expression`
- mentions `get_one_char`
- mentions `get_any_char`
- `sql_lower_text`
I am also in favor of making some of the words stand out, like the INSERT, SELECT, etc that are used throughout. Not sure if they should be in code tags or that we should use some `<samp>INSERT</samp>` mark up.
I would also like to add the tables and their respective columns to this documentation, but that will make the page very long. So perhaps it is an idea to use some sort of collapsibles / …
=> Update DBAL Documentation

development/extensions/tutorial_testing.rst
I tried to setup travis-ci according to https://area51.phpbb.com/docs/dev/3.3.x/extensions/tutorial_testing.html and could not get it running. Usually the error were:
```
$ sh -c "if [ '$IMAGE_ICC' != '0' ]; then travis/check-image-icc-profiles.sh $DB $TRAVIS_PHP_VERSION $NOTESTS; fi"
travis/check-image-icc-profiles.sh: line 20: parallel: command not found
The command "sh -c "if [ '$IMAGE_ICC' != '0' ]; then travis/check-image-icc-profiles.sh $DB $TRAVIS_PHP_VERSION $NOTESTS; fi"" exited with 127.
0.00s$ sh -c "if [ '$EPV' != '0' -a '$NOTESTS' = '1' ]; then phpBB/vendor/bin/EPV.php run --dir='phpBB/ext/$EXTNAME/'; fi"
sh: 1: phpBB/vendor/bin/EPV.php: not found
The command "sh -c "if [ '$EPV' != '0' -a '$NOTESTS' = '1' ]; then phpBB/vendor/bin/EPV.php run --dir='phpBB/ext/$EXTNAME/'; fi"" …
```
=> Update Tutorial testing travis CI config

development/language/usage.rst
Currently description says that `phpbb\language\language::add_lang()` takes the vendor + extension name as first argument and the array of language files as a second argument while it should be the opposite as shown in examples right below the description.
=> Fix the description of using add_lang() method

development/_static/css/phpbb.css, development/conf.py
Adds a simple custom stylesheet for phpBB. Biggest change is getting rid of the max-width while keeping the navigation buttons inside this max-width and adjusting the left menu header to match our colors.
This should also enable adding the event list from the wiki to the documentation.
Full page:
With some text etc:
Smartphone view:
On smaller resolutions:
=> Add custom style for phpBB w/out fixed width

development/db/dbal.rst, development/development/git.rst, development/extensions/tutorial_authentication.rst, development/extensions/tutorial_migrations.rst, development/extensions/tutorial_modules.rst, development/extensions/tutorial_notifications.rst, development/request/request.rst
According to https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html?highlight=sections#sections
Our usage of `+++` is not a proper sub subsection title convention, and should be `^^^`. There was also one title error that is fixed in here too.
This changes literally nothing in the build output of the docs, we just follow the convention with this.
=> Fix title subsection conventions and errors

development/_static/css/phpbb.css
=> Fix float issues from responsive tables

documentation/content/en/chapters/user_guide.xml
The search looks for unanswered topics, not posts and is called like t his in the quick links menu:
=> Changes posts to topics in unanswered predefined search

documentation/xsl/proteus_pdf.xsl
Tested locally and results in PDF generation working again.
Fixes #264
=> [ticket/264] Disable draft.mode when building PDF

development/extensions/database_types_list.rst, development/extensions/index.rst
=> Add Database Types Map

development/language/guidelines.rst, development/language/plurals.rst, development/language/validation.rst
Updated the link to the plural rule info page, because the old Mozilla one is dead. 
In addition some links were still to 3.2 and not implemented properly.
=> Update links to plural rules and for 3.3.x docs

development/extensions/tutorial_controllers.rst
Referencing this post I made: https://www.phpbb.com/community/viewtopic.php?p=16009966
While reading the extension documentation I came across a code example of an extension controller. The example has the use keyword before the namespace which is wrong and php throws a fatal error.
Link to the page: https://area51.phpbb.com/docs/dev/3.3.x/extensions/tutorial_controllers.html#controllers
They just need switching around and then they'll work again.
Ticket:
https://tracker.phpbb.com/browse/WEBSITE-1430
=> [ticket/1430] fix the order of use and namespace keywords in extension document

development/development/upgrade/400.rst
Documentation update for https://github.com/phpbb/phpbb/pull/6504
=> [ticket/17153] Remove deprecated functions

documentation/content/en/chapters/quick_start_guide.xml
People tend to use the newest PHP version, which is not always compatible and causes problems.
So let's limit it to 8.1 for now, since 8.2 is not yet officially supported, as we do already in the docs/ dir.
=> Include PHP 8.1, not open end with 8.2, 8.3 etc.

development/extensions/tutorial_events.rst
Requires https://github.com/phpbb/phpbb/pull/6770 to get merged.
=> Add template events prioritizing docs

development/language/guidelines.rst, development/language/validation.rst
- Updates certain examples to phpBB 4
- Remove no longer active URLs and anker
- Updates the composer.json
- Updates the file list and structure
- Add docu url to cloudflare turnstile
=> Update to respect current status of phpBB 4
